name: Package

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF/refs\/tags\//} | cut -c 2-)
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore
      run: dotnet restore ChatMate.Server/ChatMate.Server.csproj
    - name: Build
      run: dotnet build -c Release -p:Version=${{ steps.get_version.outputs.VERSION }} --no-restore ChatMate.Server/ChatMate.Server.csproj
    - name: Publish
      run: dotnet publish -c Release --no-build --no-restore --output ./publish/server ChatMate.Server/ChatMate.Server.csproj
    - name: Zip
      run: |
        cd publish/server
        zip -r "AcidBubbles.ChatMate.Server.${{ github.run_number }}.zip" *
    - name: Zip the release package
      id: zip
      run: |
        mkdir -p publish/Custom/Scripts/AcidBubbles/ChatMate
        cd ChatMate.VirtAMatePlugin
        cp -r src ../publish/Custom/Scripts/AcidBubbles/ChatMate/
        cp *.cslist ../publish/Custom/Scripts/AcidBubbles/ChatMate/
        cp meta.json ../publish/
        cd ../publish
        sed -i 's/v0.0.0/v${{ steps.get_version.outputs.VERSION }}/' meta.json
        zip -r "AcidBubbles.ChatMate.${{ github.run_number }}.var" *
    - name: GitHub release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          publish/server/AcidBubbles.ChatMate.Server.${{ github.run_number }}.zip
          publish/AcidBubbles.ChatMate.${{ github.run_number }}.var
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}